idf_component_register(
    SRCS
        "main.c"
        "app_fs.c"
        "edge_agent_version.c"
        "http_server_adapter.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        app_claw
        app_config
        settings
        claw_ramfs
        claw_utils
        official_http_server
        esp_wifi
        esp_netif
        esp_event
        nvs_flash
        fatfs
        vfs
        wear_levelling
        cjson
    PRIV_REQUIRES
        esp_system
        esp_app_format
)
